#%RAML 1.0
title: Login
version: v1.1
baseUri: http://github.com/org/folio/mod-auth/login_module

documentation:
  - title: mod-login API
    content: This module provides a username/password based login mechanism for FOLIO credentials

types:
  credential: !include credentials.json
  credentialsListObject: !include credentialsListObject.json
  loginCredentials: !include loginCredentials.json
  updateCredentials: !include updateCredentials.json
  loginAttempts: !include loginAttempts.json
  errors: !include raml-util/schemas/errors.schema
  credentialsHistory: !include credentialsHistory.json
  password: !include password.json
  passwordValid: !include passwordValid.json
  passwordReset: !include passwordResetAction.json
  passwordCreate: !include passwordCreateAction.json
  responseCreateAction: !include responseCreateAction.json
  responseResetAction: !include responseResetAction.json
  configurations: !include configurations.json
  configResponse: !include configResponse.json
  logEvent: !include logEvent.json
  logEvents: !include logEventCollection.json
  logResponse: !include logResponse.json

traits:
  validate: !include raml-util/traits/validation.raml
  pageable:
    queryParameters:
      length:
        description: "The maximum number of results to return."
        required: false
        type: integer
        example: 10
        minimum: 1
        default: 10
        maximum: 1000
      start:
        description: "The starting index in a list of results (starts at one)."
        required: false
        type: integer
        minimum: 1
        default: 1
        maximum: 1000
  sortable:
    queryParameters:
      sortBy:
        description: "A comma-separated list of fieldnames to sort by"
        required: false
        type: string
  queryable:
    queryParameters:
      query:
        description: "A query string to filter users based on matching criteria in fields."
        required: false
        type: string
/authn:
  /loginAttempts:
    /{id}:
      get:
        description: Get login attempts for a single user
        responses:
          200:
            body:
              application/json:
                schema: loginAttempts
          404:
            description: "User not found"
            body:
              text/plain:
                example: "User not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
  /login:
    post:
      description: Get a new login token
      body:
        application/json:
          type: loginCredentials
      responses:
        201:
          headers:
            x-okapi-token:
            refreshtoken:
          body:
            application/json:
              type: loginCredentials
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /update:
    post:
      description: Self-update existing credentials
      body:
        application/json:
          type: updateCredentials
      responses:
        204:
          description: "Successful update"
          body:
            text/plain: !!null
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        401:
          description: "Unauthorized"
          body:
            text/plain:
              example: "Unauthorized"
        422:
          description: "Unprocessable Entity"
          body:
            application/json:
              type: errors
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /credentials:
    get:
      description: Get a list of user credentials
      is: [
        pageable,
        sortable,
        queryable
      ]
      responses:
        200:
          body:
            application/json:
              type: credentialsListObject
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    post:
      description: Add a new login to the system
      is: [validate]
      body:
        application/json:
          type: loginCredentials
      responses:
        201:
          body:
            application/json:
              type: credential
        400:
          description: "Bad request"
          body:
            text/plain:
              example: "Bad request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    /{id}:
      get:
        description: Get login credentials for a single user
        responses:
          200:
            body:
              application/json:
                type: credential
          404:
            description: "User not found"
            body:
              text/plain:
                example: "User not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      put:
        description: Modify a user's login credentials
        body:
          application/json:
            type: loginCredentials
        responses:
          200:
            body:
              application/json:
                type: loginCredentials
          404:
            description: "User not found"
            body:
              text/plain:
                example: "User not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      delete:
        description: Remove a user's login credentials from the system
        responses:
          204:
            body:
              text/plain: !!null
          404:
            description: "User not found"
            body:
              text/plain:
                example: "User not found"
          500:
            description:
              "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
  /password:
    /repeatable:
          post:
            description: Validate password for repeatability
            body:
              application/json:
                type: password
            responses:
              200:
                body:
                  application/json:
                    type: passwordValid
              500:
                description: "Internal server error"
                body:
                  text/plain:
                    example: "Internal server error"
  /reset-password:
    post:
      description: Resets password for user in record and deletes action record
      body:
        application/json:
          schema: passwordReset
      responses:
        201:
          body:
            application/json:
              schema: responseResetAction
        400:
          body:
            text/plain:
              example: "Bad Request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
  /password-reset-action:
    post:
      description: Saves action to storage
      body:
        application/json:
          schema: passwordCreate
      responses:
        201:
          body:
            application/json:
              schema: responseCreateAction
        400:
          body:
            text/plain:
              example: "Bad Request"
        500:
          description: "Internal server error"
          body:
            text/plain:
              example: "Internal server error"
    /{actionId}:
      get:
        description: Retrieves action record by id
        responses:
          200:
            body:
              application/json:
                schema: passwordCreate
          400:
            body:
              text/plain:
                example: "Bad Request"
          404:
            body:
              text/plain:
                example: "Not Found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
  /log:
    /events:
      get:
        description: Returns a list of events retrieved from storage
        is: [
          pageable,
          queryable
        ]
        responses:
          200:
            body:
              application/json:
                schema: logEvents
          204:
            body:
              text/plain:
                example: "No Content"
          404:
            description: "Event not found"
            body:
              text/plain:
                example: "Event not found"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      post:
        description: Saves received event into the storage
        body:
          application/json:
            schema: logEvent
        responses:
          201:
            body:
              application/json:
                schema: logResponse
          204:
            body:
              text/plain:
                example: "No Content"
          500:
            description: "Internal server error"
            body:
              text/plain:
                example: "Internal server error"
      /{id}:
        delete:
          description: Removes events by filter
          responses:
            200:
              body:
                application/json:
                  schema: logResponse
            204:
              body:
                text/plain:
                  example: "No Content"
            404:
              description: "Event not found"
              body:
                text/plain:
                  example: "Event not found"
            500:
              description: "Internal server error"
              body:
                text/plain:
                  example: "Internal server error"
